import * as path from 'path';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import type { BetterSQLite3Database } from 'drizzle-orm/better-sqlite3';

/**
 * Applies the committed SQL migrations in `drizzle/` (generated by
 * `pnpm db:generate` from `schema/`). Runs synchronously on the first
 * connection; drizzle records applied migrations in `__drizzle_migrations`,
 * so re-running is a no-op.
 *
 * drizzle-kit is only used to GENERATE migrations — it cannot open the
 * SQLCipher database, so it is never pointed at `sampolio.db`.
 *
 * The folder resolves from the process working directory: `next start`,
 * `next dev`, vitest and the scripts all run from the repo root.
 */
export function getMigrationsFolder(): string {
  return path.join(process.cwd(), 'drizzle');
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function runMigrations(db: BetterSQLite3Database<any>): void {
  migrate(db, { migrationsFolder: getMigrationsFolder() });
}
